# Generated by Django 5.2.5 on 2025-12-22 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("LAUDA_VAGAS", "Lauda de Vagas")],
                        max_length=200,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                ("usuario", models.JSONField(max_length=20, verbose_name="Usuário")),
                (
                    "dados",
                    models.JSONField(
                        max_length=20000, verbose_name="JSON do Relatório"
                    ),
                ),
                ("processo_uuid", models.UUIDField(verbose_name="UUID do Processo")),
                (
                    "cabecalho",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Cabeçalho do Relatório",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
                "db_table": "relatorios",
                "ordering": ["-criado_em"],
            },
        ),
    ]
