# Generated by Django 5.2.5 on 2025-12-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relatorios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorio",
            name="dados",
            field=models.JSONField(
                default={}, max_length=20000, verbose_name="JSON do Relatório"
            ),
        ),
    ]
