# Generated by Django 5.2.5 on 2025-12-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relatorios", "0002_alter_relatorio_dados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorio",
            name="usuario",
            field=models.CharField(max_length=20, verbose_name="Usuário"),
        ),
    ]
