# Generated by Django 5.2.5 on 2026-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relatorios", "0008_popular_configuracao_resultado_escolha"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaorelatorio",
            name="usar_cabecalho_padrao",
        ),
        migrations.AddField(
            model_name="configuracaorelatorio",
            name="cabecalho_gabarito",
            field=models.TextField(
                blank=True, default="", verbose_name="Cabeçalho Gabarito"
            ),
        ),
    ]
