version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgresdb_processos_convocacao
    restart: unless-stopped
    environment:
      POSTGRES_DB: processos_convocacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - processos_convocacao_network


volumes:
  postgres_data:

networks:
  processos_convocacao_network:
    driver: bridge 