# Generated by Django 5.2.5 on 2025-09-03 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Relatório"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("agenda", "Agenda"),
                            ("convocacao", "Convocação"),
                            ("selecao", "Seleção"),
                            ("avaliacao", "Avaliação"),
                        ],
                        max_length=200,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
                "db_table": "relatorios",
                "ordering": ["-criado_em"],
            },
        ),
    ]
