# Generated by Django 5.2.5 on 2026-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relatorios", "0003_alter_relatorio_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatorio",
            name="agenda_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID da Agenda"
            ),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("LAUDA_VAGAS", "Lauda de Vagas"),
                    ("RELACAO_VAGAS", "Relação de Vagas"),
                    ("SUMULA_NAO_ESCOLHAS", "Relatório de Não Escolhas"),
                    ("LISTAGEM_ESCOLHAS_DRES", "Listagem de Escolhas por DREs"),
                    ("SUMULA_RECONVOCACAO", "Súmula de Reconvocados"),
                    ("SUMULA_ESCOLHAS", "Súmula de Escolhas"),
                    ("RECONVOCACAO", "Súmula de Reconvocados"),
                    ("LAUDA_CONVOCACAO", "Lauda de Convocação"),
                    ("LISTA_CANDIDATOS_SESSAO", "Lista de Candidatos por Sessão"),
                ],
                max_length=200,
                verbose_name="Tipo de Relatório",
            ),
        ),
    ]
