# Generated by Django 5.2.5 on 2026-01-28 20:35

import uuid
from django.db import migrations, models


def popular_configuracao_relatorio(apps, schema_editor):
    """Cria um registro de configuração para cada tipo de relatório."""
    ConfiguracaoRelatorio = apps.get_model('relatorios', 'ConfiguracaoRelatorio')
    
    # Lista de tipos de relatórios
    tipos_relatorios = [
        'LAUDA_VAGAS',
        'RELACAO_VAGAS',
        'SUMULA_NAO_ESCOLHAS',
        'LISTAGEM_ESCOLHAS_DRES',
        'SUMULA_RECONVOCACAO',
        'SUMULA_ESCOLHAS',
        'LAUDA_CONVOCACAO',
        'RESULTADO_ESCOLHA_SIM',
        'RESULTADO_ESCOLHA_NAO',
        'RESULTADO_ESCOLHA_RECONVOCACAO',
        'LISTA_CANDIDATOS_SESSAO',
        'ATA_ESCOLHA',
    ]
    
    # Cria um registro para cada tipo de relatório
    for tipo in tipos_relatorios:
        cabecalho_capa_ata = ''
        if tipo == 'ATA_ESCOLHA':
            cabecalho_capa_ata = '''
                <h1>SECRETARIA MUNICIPAL DE EDUCAÇÃO</h1><p><br></p><h3>DIVISÃO DE GESTÃO DE CARREIRAS 
                – COGEP</h3><h3>CONCURSO PÚBLICO DE INGRESSO PARA PROVIMENTO DOS CARGOS</h3>
                <h3>DE PROFESSOR DE EDUCAÇÃO INFANTIL</h3><p><br></p><p>HOMOLOGADO ATRAVÉS DO D.O.C. DE 17/06/2024, PÁGINA 337.
                </p><p><br></p><p>De acordo com a [[processo_nome]], de 12 de março de 2025, publicada no DOC de 13 de março de 2025, 
                compareceram no Auditório da COGEP/SME, Av. Angélica, 2606, no dia 28 de março de 2025, os candidatos ao cargo de
                 PROFESSOR DE EDUCAÇÃO INFANTIL, para escolhas de vagas em CARÁTER DEFINITIVO/PRECÁRIO.</p>
                 <p>Foram efetuadas, por ordem de escolha pela qual foi convocado, as escolhas registradas sob fl. 
                 numerada 01 a 01 devidamente rubricada pela Sra. _________________________________com a chancela __________.</p><p>* 
                 De acordo com a Lei 14.660 de 26/12/2007 D.O.C. 27/12/2007, artigo 123, o ato de nomeação de candidatos 
                 habilitados em concursos para provimento, em caráter efetivo, do QUADRO DOS PROFISSIONAIS DE EDUCAÇÃO, fica condicionado 
                 à prévia escolha de local de exercício.</p>
            '''

        ConfiguracaoRelatorio.objects.get_or_create(
            tipo=tipo,
            defaults={
                'usar_logotipo': False,
                'usar_cabecalho_padrao': False,
                'cabecalho': '',
                'texto_final': '',
                'cabecalho_capa_ata': cabecalho_capa_ata ,
            }
        )


def reverter_popular_configuracao_relatorio(apps, schema_editor):
    """Remove todos os registros de configuração de relatórios."""
    ConfiguracaoRelatorio = apps.get_model('relatorios', 'ConfiguracaoRelatorio')
    ConfiguracaoRelatorio.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "relatorios",
            "0005_parametrizacao_relatorio_id_alter_relatorio_tipo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoRelatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LAUDA_VAGAS", "Lauda de Vagas"),
                            ("RELACAO_VAGAS", "Relação de Vagas"),
                            ("SUMULA_NAO_ESCOLHAS", "Relatório de Não Escolhas"),
                            ("LISTAGEM_ESCOLHAS_DRES", "Listagem de Escolhas por DREs"),
                            ("SUMULA_RECONVOCACAO", "Súmula de Reconvocados"),
                            ("SUMULA_ESCOLHAS", "Súmula de Escolhas"),                            
                            ("LAUDA_CONVOCACAO", "Lauda de Convocação"),
                            (
                                "RESULTADO_ESCOLHA_SIM",
                                "Resultado de Escolha de vagas - Sim",
                            ),
                            (
                                "RESULTADO_ESCOLHA_NAO",
                                "Resultado de Escolha de vagas - Não",
                            ),
                            (
                                "RESULTADO_ESCOLHA_RECONVOCACAO",
                                "Resultado de Escolha de vagas - Reconvocação",
                            ),
                            (
                                "LISTA_CANDIDATOS_SESSAO",
                                "Lista de Candidatos por Sessão",
                            ),
                            ("ATA_ESCOLHA", "Ata de Escolha"),
                        ],
                        max_length=200,
                        unique=True,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                (
                    "usar_logotipo",
                    models.BooleanField(default=False, verbose_name="Usar Logotipo"),
                ),
                (
                    "usar_cabecalho_padrao",
                    models.BooleanField(
                        default=False, verbose_name="Usar Cabeçalho Padrão"
                    ),
                ),
                (
                    "cabecalho",
                    models.TextField(blank=True, default="", verbose_name="Cabeçalho"),
                ),
                (
                    "texto_final",
                    models.TextField(
                        blank=True, default="", verbose_name="Texto Final"
                    ),
                ),
                (
                    "cabecalho_capa_ata",
                    models.TextField(
                        blank=True, default="", verbose_name="Cabeçalho Capa da Ata"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Relatório",
                "verbose_name_plural": "Configurações de Relatórios",
                "db_table": "relatorios_configuracao",
                "ordering": ["tipo"],
            },
        ),
        migrations.AddField(
            model_name="relatorio",
            name="cabecalho_capa_ata",
            field=models.TextField(
                blank=True, null=True, verbose_name="Cabeçalho Capa da Ata"
            ),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="texto_final",
            field=models.TextField(blank=True, null=True, verbose_name="Texto Final"),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="usou_cabecalho_padrao",
            field=models.BooleanField(
                default=False, verbose_name="Usou Cabeçalho Padrão"
            ),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="usou_logotipo",
            field=models.BooleanField(default=False, verbose_name="Usou Logotipo"),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("LAUDA_VAGAS", "Lauda de Vagas"),
                    ("RELACAO_VAGAS", "Relação de Vagas"),
                    ("SUMULA_NAO_ESCOLHAS", "Relatório de Não Escolhas"),
                    ("LISTAGEM_ESCOLHAS_DRES", "Listagem de Escolhas por DREs"),
                    ("SUMULA_RECONVOCACAO", "Súmula de Reconvocados"),
                    ("SUMULA_ESCOLHAS", "Súmula de Escolhas"),                    
                    ("LAUDA_CONVOCACAO", "Lauda de Convocação"),
                    ("RESULTADO_ESCOLHA_SIM", "Resultado de Escolha de vagas - Sim"),
                    ("RESULTADO_ESCOLHA_NAO", "Resultado de Escolha de vagas - Não"),
                    (
                        "RESULTADO_ESCOLHA_RECONVOCACAO",
                        "Resultado de Escolha de vagas - Reconvocação",
                    ),
                    ("LISTA_CANDIDATOS_SESSAO", "Lista de Candidatos por Sessão"),
                    ("ATA_ESCOLHA", "Ata de Escolha"),
                ],
                max_length=200,
                verbose_name="Tipo de Relatório",
            ),
        ),
        migrations.RunPython(
            popular_configuracao_relatorio,
            reverter_popular_configuracao_relatorio
        ),
    ]
