# Generated by Django 5.2.5 on 2026-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "relatorios",
            "0006_configuracaorelatorio_relatorio_cabecalho_capa_ata_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaorelatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("LAUDA_VAGAS", "Lauda de Vagas"),
                    ("RELACAO_VAGAS", "Relação de Vagas"),
                    ("SUMULA_NAO_ESCOLHAS", "Relatório de Não Escolhas"),
                    ("LISTAGEM_ESCOLHAS_DRES", "Listagem de Escolhas por DREs"),
                    ("SUMULA_RECONVOCACAO", "Súmula de Reconvocados"),
                    ("SUMULA_ESCOLHAS", "Súmula de Escolhas"),
                    ("LAUDA_CONVOCACAO", "Lauda de Convocação"),
                    ("RESULTADO_ESCOLHA", "Resultado de Escolha de Vagas"),
                    ("LISTA_CANDIDATOS_SESSAO", "Lista de Candidatos por Sessão"),
                    ("ATA_ESCOLHA", "Ata de Escolha"),
                ],
                max_length=200,
                unique=True,
                verbose_name="Tipo de Relatório",
            ),
        ),
        migrations.AlterField(
            model_name="relatorio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("LAUDA_VAGAS", "Lauda de Vagas"),
                    ("RELACAO_VAGAS", "Relação de Vagas"),
                    ("SUMULA_NAO_ESCOLHAS", "Relatório de Não Escolhas"),
                    ("LISTAGEM_ESCOLHAS_DRES", "Listagem de Escolhas por DREs"),
                    ("SUMULA_RECONVOCACAO", "Súmula de Reconvocados"),
                    ("SUMULA_ESCOLHAS", "Súmula de Escolhas"),
                    ("LAUDA_CONVOCACAO", "Lauda de Convocação"),
                    ("RESULTADO_ESCOLHA", "Resultado de Escolha de Vagas"),
                    ("LISTA_CANDIDATOS_SESSAO", "Lista de Candidatos por Sessão"),
                    ("ATA_ESCOLHA", "Ata de Escolha"),
                ],
                max_length=200,
                verbose_name="Tipo de Relatório",
            ),
        ),
    ]
