# Generated by Django 5.2.5 on 2026-02-12

from django.db import migrations


def popular_configuracao_resultado_escolha(apps, schema_editor):
    """Cria registro de configuração para o tipo RESULTADO_ESCOLHA."""
    ConfiguracaoRelatorio = apps.get_model('relatorios', 'ConfiguracaoRelatorio')

    ConfiguracaoRelatorio.objects.get_or_create(
        tipo='RESULTADO_ESCOLHA',
        defaults={
            'usar_logotipo': False,
            'usar_cabecalho_padrao': False,
            'cabecalho': '',
            'texto_final': '',
            'cabecalho_capa_ata': '',
        }
    )


def reverter_popular_configuracao_resultado_escolha(apps, schema_editor):
    """Remove o registro de configuração do tipo RESULTADO_ESCOLHA."""
    ConfiguracaoRelatorio = apps.get_model('relatorios', 'ConfiguracaoRelatorio')
    ConfiguracaoRelatorio.objects.filter(tipo='RESULTADO_ESCOLHA').delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "relatorios",
            "0007_alter_configuracaorelatorio_tipo_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(popular_configuracao_resultado_escolha, reverter_popular_configuracao_resultado_escolha),
    ]
